version: 2.1
orbs:
  discord: antonioned/discord@0.1.0
  discord-win: gelmo/discord-win@0.0.2
  win: circleci/windows@5.0
jobs:
  build-linux64:
    docker:
      - image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
      DEBCONF_NONINTERACTIVE_SEEN: true
    steps:
      - run: apt update
      - run: apt install -y openssh-client git # CircleCI Deps
      - run: apt install -y curl clang cmake build-essential libsdl2-dev libopenal-dev libvorbis-dev libfreetype6-dev libcurl4-gnutls-dev git zip unzip
      - checkout
      - run: curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
      - run: unzip third-party/steamworks/sdk.zip -d third-party/steamworks
      - run: export CC=clang CXX=clang++
      - run: cmake -DBUILD_STEAMLIB=1 ./source
      - run: make -j8
      - run: tar -czvf ./source/Linux-x86_64-Release.tar.gz ./source/build/* --exclude ./source/build/*.a --exclude ./source/build/base*/*.a ./source/build/libs/*.a
      - discord/status:
          fail_only: false
          failure_message: ":red_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has failed!"
          success_message: ":green_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has succeeded!"
          webhook: "${DISCORD_STATUS_WEBHOOK}"
      - store_artifacts:
          path: ./source/Linux-x86_64-Release.tar.gz

  build-linux64-debug:
    docker:
      - image: ubuntu:20.04
    environment:
      DEBIAN_FRONTEND: noninteractive
      DEBCONF_NONINTERACTIVE_SEEN: true
    steps:
      - run: apt update
      - run: apt install -y openssh-client git # CircleCI Deps
      - run: apt install -y curl clang cmake build-essential libsdl2-dev libopenal-dev libvorbis-dev libfreetype6-dev libcurl4-gnutls-dev git zip unzip
      - checkout
      - run: curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
      - run: unzip third-party/steamworks/sdk.zip -d third-party/steamworks
      - run: export CC=clang CXX=clang++
      - run: cmake -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_STEAMLIB=1 ./source
      - run: make -j8
      - run: tar -czvf ./source/Linux-x86_64-Debug.tar.gz ./source/build/* --exclude ./source/build/*.a --exclude ./source/build/base*/*.a ./source/build/libs/*.a
      - discord/status:
          fail_only: false
          failure_message: ":red_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has failed!"
          success_message: ":green_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has succeeded!"
          webhook: "${DISCORD_STATUS_WEBHOOK}"
      - store_artifacts:
          path: ./source/Linux-x86_64-Debug.tar.gz          

  build-osx:
    macos:
      xcode: '13.4.1'
    steps:
      - checkout
      - run: brew update
      - run: brew install curl cmake sdl2 openal-soft libvorbis freetype git zip unzip
      - run: curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
      - run: unzip third-party/steamworks/sdk.zip -d third-party/steamworks
      - run: cmake -DBUILD_STEAMLIB=1 -G Xcode ./source
      - run: xcodebuild -project qfusion.xcodeproj/ -jobs 4 -configuration Release -target ALL_BUILD CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - run: tar -czvf ./source/OSX-x86_64-Release.tar.gz ./source/build/Release/*.app
      - discord/status:
          fail_only: false
          failure_message: ":red_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has failed!"
          success_message: ":green_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has succeeded!"
          webhook: "${DISCORD_STATUS_WEBHOOK}"
      - store_artifacts:
          path: ./source/OSX-x86_64-Release.tar.gz

  build-osx-debug:
    macos:
      xcode: '13.4.1'
    steps:
      - checkout
      - run: brew update
      - run: brew install curl cmake sdl2 openal-soft libvorbis freetype git zip unzip
      - run: curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
      - run: unzip third-party/steamworks/sdk.zip -d third-party/steamworks
      - run: cmake -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_STEAMLIB=1 -DWF_BUILD_DSYM=ON -G Xcode ./source
      - run: xcodebuild -project qfusion.xcodeproj/ -jobs 4 -configuration Debug -target ALL_BUILD CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - run: tar -czvf ./source/OSX-x86_64-Debug.tar.gz ./source/build/Debug/*.app
      - discord/status:
          fail_only: false
          failure_message: ":red_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has failed!"
          success_message: ":green_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has succeeded!"
          webhook: "${DISCORD_STATUS_WEBHOOK}"
      - store_artifacts:
          path: ./source/OSX-x86_64-Debug.tar.gz

  build-win64:
    executor:
        name: win/server-2019
        shell: cmd.exe
    steps:
      - checkout
      - run: choco install cmake -y
      - run: curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
      - run: 7z x third-party/steamworks/sdk.zip -othird-party/steamworks
      - run:
         command: cd source; C:\PROGRA~1\CMake\bin\cmake.exe -G "Visual Studio 16 2019" -A "x64" -T "v142" -DBUILD_STEAMLIB=1 .
         shell: powershell.exe
      - run: msbuild .\source\qfusion.sln /p:configuration=Release /maxcpucount:8
      - run: 7z a win-x86_64-Release.zip .\source\build\Release\* -r -x!*.exp -x!*.lib
      - discord-win/status:
          fail_only: false
          failure_message: ":red_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has failed!"
          success_message: ":green_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has succeeded!"
          webhook: "${DISCORD_STATUS_WEBHOOK}"
      - store_artifacts:
          path: .\win-x86_64-Release.zip

  build-win64-debug:
    executor:
        name: win/server-2019
        shell: cmd.exe
    steps:
      - checkout
      - run: choco install cmake -y
      - run: curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
      - run: 7z x third-party/steamworks/sdk.zip -othird-party/steamworks
      - run:
         command: cd source; C:\PROGRA~1\CMake\bin\cmake.exe -G "Visual Studio 16 2019" -A "x64" -T "v142" -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_STEAMLIB=1 .
         shell: powershell.exe
      - run: msbuild .\source\qfusion.sln /p:configuration=Debug /maxcpucount:8
      - run: 7z a win-x86_64-Debug.zip .\source\build\Debug\* -r -x!*.exp -x!*.lib
      - discord-win/status:
          fail_only: false
          failure_message: ":red_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has failed!"
          success_message: ":green_circle: ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_BRANCH} ${CIRCLE_JOB} (${CIRCLE_SHA1}) has succeeded!"
          webhook: "${DISCORD_STATUS_WEBHOOK}"
      - store_artifacts:
          path: .\win-x86_64-Debug.zip

workflows:
  version: 2
  build:
    jobs:
      - build-linux64
      - build-linux64-debug
      - build-osx
      - build-osx-debug
      - build-win64
      - build-win64-debug
