name: Build

on: [push, pull_request]

jobs:

  build-linux64:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04
      env:
        DEBIAN_FRONTEND: noninteractive
        DEBCONF_NONINTERACTIVE_SEEN: true
    steps:
      - name: Update git before checkout - https://github.com/actions/checkout/issues/335
        run: |
          apt update
          apt install -y git

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add safe directory - https://github.com/actions/checkout/issues/1169
        run: git config --system --add safe.directory /__w/warfork-qfusion/warfork-qfusion

      - name: Install build dependencies
        run: |
          apt update
          apt install -y curl clang cmake build-essential libsdl2-dev libopenal-dev libvorbis-dev libfreetype6-dev libcurl4-gnutls-dev git zip unzip

      - name: Download steamworks sdk
        run: |
          curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
          unzip third-party/steamworks/sdk.zip -d third-party/steamworks

      - name: Generate makefiles
        working-directory: ./source
        run: |
          export CC=clang CXX=clang++
          cmake -DBUILD_STEAMLIB=1 .

      - name: Build project
        working-directory: ./source
        run: make -j8
      
      - name: Package warfork
        working-directory: ./source/build
        run: tar -czvf ../Linux-x86_64-Release.tar.gz * --exclude *.a --exclude base*/*.a libs/*.a

      - name: Upload warfork artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-release
          path: source/Linux-x86_64-Release.tar.gz

  build-linux64-debug:
    runs-on: ubuntu-20.04
    container:
      image: ubuntu:20.04
      env:
        DEBIAN_FRONTEND: noninteractive
        DEBCONF_NONINTERACTIVE_SEEN: true
    steps:
      - name: Update git before checkout - https://github.com/actions/checkout/issues/335
        run: |
          apt update
          apt install -y git

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add safe directory - https://github.com/actions/checkout/issues/1169
        run: git config --system --add safe.directory /__w/warfork-qfusion/warfork-qfusion

      - name: Install build dependencies
        run: |
          apt update
          apt install -y curl clang cmake build-essential libsdl2-dev libopenal-dev libvorbis-dev libfreetype6-dev libcurl4-gnutls-dev git zip unzip

      - name: Download steamworks sdk
        run: |
          curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
          unzip third-party/steamworks/sdk.zip -d third-party/steamworks

      - name: Generate makefiles
        working-directory: ./source
        run: |
          export CC=clang CXX=clang++
          cmake -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_STEAMLIB=1 .

      - name: Build project
        working-directory: ./source
        run: make -j8
      
      - name: Package warfork
        working-directory: ./source/build
        run: tar -czvf ../Linux-x86_64-Debug.tar.gz * --exclude *.a --exclude base*/*.a libs/*.a

      - name: Upload warfork artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-debug
          path: source/Linux-x86_64-Debug.tar.gz

  build-osx:
    runs-on: macos-12
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'

      - name: Install build dependencies
        run: |
          brew uninstall --force azure-cli
          brew uninstall --force aws-sam-cli
          brew install python@3 || brew link --overwrite python@3
          brew update
          brew install curl cmake sdl2 openal-soft libvorbis freetype git zip unzip

      - name: Download steamworks sdk
        run: |
          curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
          unzip third-party/steamworks/sdk.zip -d third-party/steamworks

      - name: Generate makefiles
        working-directory: ./source
        run: cmake -DBUILD_STEAMLIB=1 -G Xcode .

      - name: Build project
        working-directory: ./source
        run: xcodebuild -project qfusion.xcodeproj/ -jobs 4 -configuration Release -target ALL_BUILD CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
      - name: Package warfork
        working-directory: ./source/build
        run: tar -czvf ../OSX-x86_64-Release.tar.gz Release/*.app

      - name: Upload warfork artifact
        uses: actions/upload-artifact@v3
        with:
          name: osx-x86_64-release
          path: source/OSX-x86_64-Release.tar.gz

  build-osx-debug:
    runs-on: macos-12
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'

      - name: Install build dependencies
        run: |
          brew uninstall --force azure-cli
          brew uninstall --force aws-sam-cli
          brew install python@3 || brew link --overwrite python@3
          brew update
          brew install curl cmake sdl2 openal-soft libvorbis freetype git zip unzip

      - name: Download steamworks sdk
        run: |
          curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
          unzip third-party/steamworks/sdk.zip -d third-party/steamworks

      - name: Generate makefiles
        working-directory: ./source
        run: cmake -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_STEAMLIB=1 -DWF_BUILD_DSYM=ON -G Xcode .

      - name: Build project
        working-directory: ./source
        run: xcodebuild -project qfusion.xcodeproj/ -jobs 4 -configuration Debug -target ALL_BUILD CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      
      - name: Package warfork
        working-directory: ./source/build
        run: tar -czvf ../OSX-x86_64-Debug.tar.gz Debug/*.app

      - name: Upload warfork artifact
        uses: actions/upload-artifact@v3
        with:
          name: osx-x86_64-debug
          path: source/OSX-x86_64-Debug.tar.gz

  build-win64:
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download steamworks sdk
        run: |
          curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
          7z x third-party/steamworks/sdk.zip -othird-party/steamworks

      - name: Generate makefiles
        working-directory: .\source
        run: cmake -G "Visual Studio 16 2019" -A x64 -T "v142" -DBUILD_STEAMLIB=1 .

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build project
        working-directory: .\source
        run: msbuild qfusion.sln /p:configuration=Release /maxcpucount:8

      - name: Package warfork
        working-directory: .\source\build\Release
        run: 7z a ..\..\win-x86_64-Release.zip * '-xr!*.exp' '-xr!*.lib'

      - name: Upload warfork artifact
        uses: actions/upload-artifact@v3
        with:
          name: win-x86_64-release
          path: source\win-x86_64-Release.zip

  build-win64-debug:
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download steamworks sdk
        run: |
          curl https://warfork.com/downloads/sdk/ --output third-party/steamworks/sdk.zip
          7z x third-party/steamworks/sdk.zip -othird-party/steamworks

      - name: Generate makefiles
        working-directory: .\source
        run: cmake -G "Visual Studio 16 2019" -A x64 -T "v142" -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_STEAMLIB=1 .

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Build project
        working-directory: .\source
        run: msbuild qfusion.sln /p:configuration=Debug /maxcpucount:8

      - name: Package warfork
        working-directory: .\source\build\Debug
        run: 7z a ..\..\win-x86_64-Debug.zip * '-xr!*.exp' '-xr!*.lib'

      - name: Upload warfork artifact
        uses: actions/upload-artifact@v3
        with:
          name: win-x86_64-debug
          path: source\win-x86_64-Debug.zip
